[no-cd]
default:
    uv run python source_download.py usgs3dep1m
    uv run python source_slice.py usgs3dep1m 16384
    uv run python 
    uv run python source_to_cog.py usgs3dep1m
    uv run python source_bounds.py usgs3dep1m
    uv run python source_polygonize.py usgs3dep1m 32
    uv run python source_create_tarball.py usgs3dep1m
